version: '3'

services:
  mongo:
    image: mongo
    volumes:
    - ./mongo:/data/db

  wiki:
    build: ./wiki
    volumes:
    - ./repo:/var/wiki/repo:rw,z
    environment:
    - WIKI_HOST=https://127.0.0.1:443
    - WIKI_ADMIN_EMAIL=admin@example.com
    depends_on:
      - mongo
